---
name: ストーリー
about: ユーザーストーリー
title: "[STORY] 〜をする、〜をしたい"
labels: story
assignees: ''

---

## ストーリーの目的

<!-- - このストーリーによってユーザーが得られる価値はなんでしょうか -->

## 経緯・背景

<!-- - このストーリーが作られた経緯があれば記載します -->

## 実現方法

<!-- - このストーリーを実現するための方法はなんでしょうか -->

## 受入条件・完了の定義

<!-- - ストーリーが達成されたことを確認する条件を箇条書きします -->

## 詳細タスク

```[tasklist]
### 要件定義
- [ ] 仕様案の検討
- [ ] UI草案作成
- [ ] 仕様書作成
- [ ] UIの修正・決定 
```

```[tasklist]
### 設計
- [ ] API外部設計
- [ ] DB設計
- [ ] API詳細設計
- [ ] マイグレーションの設計
```
```[tasklist]
### フロント実装
- [ ] ~画面の実装
```
```[tasklist]
### バックエンド実装
- [ ] ~APIの実装
```
```[tasklist]
### テスト
- [ ] テスト設計
- [ ] テスト実施
```

```[tasklist]
### その他
- [ ] マニュアル作成
- [ ] リリースノート作成
- [ ] リリース計画
```
